### ISSUE TITLE
mpv-lastfm.lua: deprecated settings directory

### ISSUE THREAD

**Issue by rien333** [l29ah/w3crapcli#9]
I'm not sure what is exacly required to fix it, but using your lastfm script for scrobbling with mpv shows a warning message about the mpv config direcoty having moved from `lua-settings` to `script-opts`. Seems pretty trivial but I couldn't find a fix.

**Comment by l29ah** [comment]
`mv ~/.mpv/lua-settings ~/.mpv/script-ops`

**Comment by rien333** [comment]
Already tried that, didn't work for me. (kinda odd isn't it?)

**Comment by l29ah** [comment]
Check `strace` then (maybe your `$HOME` or XDG dirs are somewhere unusual?).

**Comment by rien333** [comment]
My config dir is the default Linux one I think, `~/.config/mpv` (`~/.mpv` is more macOS i think?). I'll check strace.

**Comment by rien333** [comment]
Okay strace is a little bit too much (mpv outputs a lot of stuff and idc enough about the warning to learn strace) so for now I'll link lua-settings to script-opts.

**Comment by l29ah** [comment]
2>&1 | grep lua-settings
